# Generated by Django 3.2.3 on 2021-06-25 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_aircraft'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flights.flight'),
            preserve_default=False,
        ),
    ]
