# Generated by Django 3.2.4 on 2021-06-25 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_passenger',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passengers.passenger'),
            preserve_default=False,
        ),
    ]
