# Generated by Django 3.2.4 on 2021-06-28 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
        ('tickets', '0003_alter_ticket_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Preco')),
                ('extra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='extras.extra')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Item extra',
                'verbose_name_plural': 'Itens extras',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='extra_item',
            field=models.ManyToManyField(blank=True, through='tickets.ExtraItem', to='extras.Extra'),
        ),
    ]
