# Generated by Django 3.2.4 on 2021-06-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='Voo cheio'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aircrafts.aircraft'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Tickets'),
        ),
    ]
