# Generated by Django 3.2.4 on 2021-06-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20210617_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='quantity',
        ),
    ]
