# Generated by Django 3.2.4 on 2021-06-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_flight_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Tickets'),
        ),
    ]
