# Generated by Django 3.2.3 on 2021-06-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('flights', '0003_flight_cod_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='city_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_from', to='cities.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='city_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_to', to='cities.city'),
            preserve_default=False,
        ),
    ]
