# Generated by Django 3.2.4 on 2021-06-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0001_initial'),
        ('flights', '0004_flight_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircrafts.aircraft')),
            ],
            options={
                'verbose_name': 'Aeronave do voo',
                'verbose_name_plural': 'Aeronaves do voo',
                'ordering': ['id'],
            },
        ),
    ]
