# Generated by Django 3.2.3 on 2021-06-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20210627_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='city_from',
        ),
        migrations.RemoveField(
            model_name='route',
            name='city_to',
        ),
    ]
